
import { Invoice, Project, Task } from './types';

export const mockUser = {
  uid: '12345',
  email: 'freelancer@forge.com',
  name: 'Alex Dubois',
  company: 'Alex Dubois Creative',
  phone: '+1 234 567 890',
  avatar: 'user-avatar',
  role: 'freelancer' as const,
};

export const mockProjects: Project[] = [
  {
    id: 'proj1',
    userId: '12345',
    name: 'E-commerce Platform',
    client: 'Innovate Inc.',
    description: 'Full-stack development of a new e-commerce platform.',
    status: 'In Progress',
    progress: 65,
    budget: 25000,
    startDate: '2023-01-15',
    endDate: '2023-06-30',
  },
  {
    id: 'proj2',
    userId: '12345',
    name: 'Mobile App Design',
    client: 'StartupX',
    description: 'UI/UX design for a new social media mobile app.',
    status: 'Completed',
    progress: 100,
    budget: 12000,
    startDate: '2023-03-01',
    endDate: '2023-05-10',
  },
  {
    id: 'proj3',
    userId: '12345',
    name: 'Marketing Website',
    client: 'Growth Co.',
    description: 'Redesign and development of the main marketing website.',
    status: 'Planning',
    progress: 15,
    budget: 8000,
    startDate: '2023-07-01',
    endDate: '2023-09-01',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task1',
    userId: '12345',
    title: 'Setup database schema',
    description: 'Design and implement the primary database schema for the e-commerce platform.',
    projectId: 'proj1',
    projectName: 'E-commerce Platform',
    status: 'Done',
    priority: 'High',
    dueDate: '2023-01-30',
  },
  {
    id: 'task2',
    userId: '12345',
    title: 'Develop authentication flow',
    description: 'Implement user registration and login functionality.',
    projectId: 'proj1',
    projectName: 'E-commerce Platform',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2023-02-15',
  },
  {
    id: 'task3',
    userId: '12345',
    title: 'Create wireframes for homepage',
    description: 'Design low-fidelity wireframes for the mobile app homepage.',
    projectId: 'proj2',
    projectName: 'Mobile App Design',
    status: 'Done',
    priority: 'Medium',
    dueDate: '2023-03-15',
  },
  {
    id: 'task4',
    userId: '12345',
    title: 'Define project scope',
    description: 'Meet with stakeholders to define the scope for the marketing website.',
    projectId: 'proj3',
    projectName: 'Marketing Website',
    status: 'Todo',
    priority: 'Critical',
    dueDate: '2023-07-05',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    userId: '12345',
    invoiceNumber: 'INV-2023-001',
    client: 'StartupX',
    amount: 12000,
    status: 'Paid',
    issueDate: '2023-05-11',
    dueDate: '2023-05-26',
    description: 'Final payment for Mobile App Design project.',
    items: [{ description: 'UI/UX Design Services', quantity: 1, unitPrice: 12000, total: 12000 }],
  },
  {
    id: 'inv2',
    userId: '12345',
    invoiceNumber: 'INV-2023-002',
    client: 'Innovate Inc.',
    amount: 10000,
    status: 'Sent',
    issueDate: '2023-04-01',
    dueDate: '2023-04-15',
    description: 'Milestone 2 payment for E-commerce Platform.',
    items: [{ description: 'Backend Development Milestone', quantity: 1, unitPrice: 10000, total: 10000 }],
  },
  {
    id: 'inv3',
    userId: '12345',
    invoiceNumber: 'INV-2023-003',
    client: 'Random Corp',
    amount: 2500,
    status: 'Overdue',
    issueDate: '2023-03-15',
    dueDate: '2023-03-30',
    description: 'Consulting services for Q1.',
    items: [{ description: 'Hourly Consulting', quantity: 25, unitPrice: 100, total: 2500 }],
  },
    {
    id: 'inv4',
    userId: '12345',
    invoiceNumber: 'INV-2023-004',
    client: 'Innovate Inc.',
    amount: 5000,
    status: 'Draft',
    issueDate: '2023-06-01',
    dueDate: '2023-06-15',
    description: 'Milestone 3 payment.',
    items: [{ description: 'Frontend Development Milestone', quantity: 1, unitPrice: 5000, total: 5000 }],
  },
];
